// <auto-generated />
using System;
using Backend.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(MusicCoreContext))]
    partial class MusicCoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Service.Models.Artista", b =>
                {
                    b.Property<int>("ArtistaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ArtistaId"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ArtistaId");

                    b.ToTable("Artistas");

                    b.HasData(
                        new
                        {
                            ArtistaId = 1,
                            IsDeleted = false,
                            Nombre = "The Beatles"
                        },
                        new
                        {
                            ArtistaId = 2,
                            IsDeleted = false,
                            Nombre = "Michael Jackson"
                        },
                        new
                        {
                            ArtistaId = 3,
                            IsDeleted = false,
                            Nombre = "Madonna"
                        });
                });

            modelBuilder.Entity("Service.Models.Cancion", b =>
                {
                    b.Property<int>("CancionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CancionId"));

                    b.Property<int>("DiscoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Duracion")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("CancionId");

                    b.HasIndex("DiscoId");

                    b.ToTable("Canciones");

                    b.HasData(
                        new
                        {
                            CancionId = 1,
                            DiscoId = 1,
                            Duracion = 4.20m,
                            IsDeleted = false,
                            Titulo = "Come Together"
                        },
                        new
                        {
                            CancionId = 2,
                            DiscoId = 2,
                            Duracion = 4.54m,
                            IsDeleted = false,
                            Titulo = "Billie Jean"
                        },
                        new
                        {
                            CancionId = 3,
                            DiscoId = 3,
                            Duracion = 4.00m,
                            IsDeleted = false,
                            Titulo = "Material Girl"
                        });
                });

            modelBuilder.Entity("Service.Models.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ClienteId"));

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ClienteId");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            ClienteId = 1,
                            Email = "perezJuan@gmail.com",
                            IsDeleted = false,
                            Nombre = "Juan Perez"
                        },
                        new
                        {
                            ClienteId = 2,
                            Email = "gomezMaria@gmail.com",
                            IsDeleted = false,
                            Nombre = "Maria Gomez"
                        },
                        new
                        {
                            ClienteId = 3,
                            Email = "sanchezCarlos@gmail.com",
                            IsDeleted = false,
                            Nombre = "Carlos Sanchez"
                        });
                });

            modelBuilder.Entity("Service.Models.Disco", b =>
                {
                    b.Property<int>("DiscoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DiscoId"));

                    b.Property<int>("ArtistaId")
                        .HasColumnType("int");

                    b.Property<int>("GeneroId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("DiscoId");

                    b.HasIndex("ArtistaId");

                    b.HasIndex("GeneroId");

                    b.ToTable("Discos");

                    b.HasData(
                        new
                        {
                            DiscoId = 1,
                            ArtistaId = 1,
                            GeneroId = 1,
                            IsDeleted = false,
                            Titulo = "Abbey Road"
                        },
                        new
                        {
                            DiscoId = 2,
                            ArtistaId = 2,
                            GeneroId = 2,
                            IsDeleted = false,
                            Titulo = "Thriller"
                        },
                        new
                        {
                            DiscoId = 3,
                            ArtistaId = 3,
                            GeneroId = 2,
                            IsDeleted = false,
                            Titulo = "Like a Virgin"
                        });
                });

            modelBuilder.Entity("Service.Models.Genero", b =>
                {
                    b.Property<int>("GeneroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("GeneroId"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("GeneroId");

                    b.ToTable("Generos");

                    b.HasData(
                        new
                        {
                            GeneroId = 1,
                            IsDeleted = false,
                            Nombre = "Rock"
                        },
                        new
                        {
                            GeneroId = 2,
                            IsDeleted = false,
                            Nombre = "Pop"
                        },
                        new
                        {
                            GeneroId = 3,
                            IsDeleted = false,
                            Nombre = "Jazz"
                        });
                });

            modelBuilder.Entity("Service.Models.Venta", b =>
                {
                    b.Property<int>("VentaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("VentaId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int>("DiscoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("VentaId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("DiscoId");

                    b.ToTable("Ventas");

                    b.HasData(
                        new
                        {
                            VentaId = 1,
                            Cantidad = 1,
                            ClienteId = 1,
                            DiscoId = 1,
                            Fecha = new DateTime(2025, 8, 24, 16, 45, 11, 40, DateTimeKind.Local).AddTicks(9975),
                            IsDeleted = false,
                            Precio = 95000m
                        },
                        new
                        {
                            VentaId = 2,
                            Cantidad = 2,
                            ClienteId = 2,
                            DiscoId = 2,
                            Fecha = new DateTime(2025, 8, 24, 16, 45, 11, 40, DateTimeKind.Local).AddTicks(9989),
                            IsDeleted = false,
                            Precio = 70000m
                        },
                        new
                        {
                            VentaId = 3,
                            Cantidad = 1,
                            ClienteId = 3,
                            DiscoId = 3,
                            Fecha = new DateTime(2025, 8, 24, 16, 45, 11, 40, DateTimeKind.Local).AddTicks(9991),
                            IsDeleted = false,
                            Precio = 80000m
                        });
                });

            modelBuilder.Entity("Service.Models.Cancion", b =>
                {
                    b.HasOne("Service.Models.Disco", "Disco")
                        .WithMany("Canciones")
                        .HasForeignKey("DiscoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Disco");
                });

            modelBuilder.Entity("Service.Models.Disco", b =>
                {
                    b.HasOne("Service.Models.Artista", "Artista")
                        .WithMany()
                        .HasForeignKey("ArtistaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Service.Models.Genero", "Genero")
                        .WithMany()
                        .HasForeignKey("GeneroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artista");

                    b.Navigation("Genero");
                });

            modelBuilder.Entity("Service.Models.Venta", b =>
                {
                    b.HasOne("Service.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Service.Models.Disco", "Disco")
                        .WithMany()
                        .HasForeignKey("DiscoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Disco");
                });

            modelBuilder.Entity("Service.Models.Disco", b =>
                {
                    b.Navigation("Canciones");
                });
#pragma warning restore 612, 618
        }
    }
}
